# Generated by Django 3.1.7 on 2021-03-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='provider_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
