# Generated by Django 3.1.7 on 2021-03-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0002_auto_20210305_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='compressed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
